services:
  - type: web
    name: iti-house-price-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
